### PR TITLE
GTK4 Port

### PR DESCRIPTION
**Pull request by me00001**
Related https://github.com/xlmnxp/blue-recorder/pull/39

### CODE REVIEW

**Comment by me00001** [comment]
> Build [76994 successful](https://buildbot.flathub.org/#/builders/6/builds/76994) To test this build, install it from the testing repository:
> 
> 
> flatpak install --user https://dl.flathub.org/build-repo/59581/sa.sy.bluerecorder.flatpakref
> ```
```
thread 'main' panicked at src/wayland_record.rs:221:14:
failed to start pipeline: StateChangeError
```

https://github.com/ochibani/blue-recorder/blob/4e4756e88a83dc76bad0eedad7e723e13e63849a/src/wayland_record.rs#L219-L223

**Comment by xlmnxp** [comment]
@me00001 I think you need to replace `org.gnome.Shell.Screencast` with `org.freedesktop.portal.ScreenCast` in `sa.sy.bluerecorder.yaml`

**Comment by me00001** [comment]
`flatpak run --talk-name=org.freedesktop.portal.ScreenCast sa.sy.bluerecorder`

**Comment by me00001** [comment]
bot, build sa.sy.bluerecorder

**Pull request merged**
